### ISSUE TITLE
Pushing fails for files in importable subfolder

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-cli#34]
Here is a traceback:
` $ viur script push
There is no file named importer.py. Create it? [y/N]: y
Push scripts/importer.py
There is no file named exporter.py. Create it? [y/N]: y
Push scripts/exporter.py
There is no folder named importable/. Create it? [y/N]: y
Push scripts/importable
There is no file named importable/impexp.py. Create it? [y/N]: y
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/cli.py", line 220, in main
    entry = await anext(tree.list(_type, {"path": file}))
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/scriptor/viur.py", line 195, in __anext__
    return await self.__anext__()
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/scriptor/viur.py", line 178, in __anext__
    raise StopAsyncIteration
StopAsyncIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/bin/viur", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/cli.py", line 289, in push
    asyncio.new_event_loop().run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/cli.py", line 255, in main
    parent_entry = await anext(tree.list("node", {"path": parent}))
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/scriptor/viur.py", line 195, in __anext__
    return await self.__anext__()
  File "/home/user/.local/share/virtualenvs/project-viur3-s2IdUEXK/lib/python3.10/site-packages/viur_cli/scriptor/scriptor/viur.py", line 178, in __anext__
    raise StopAsyncIteration
StopAsyncIteration`

**Comment by Grashalmbeisser** [comment]
Is this Bug still present, i was not able to reproduce it? @xnopasaranx

**Comment by KadirBalku** [comment]
afaik this is solved in 2.3.1
