### ISSUE TITLE
`requests` is missing as dependency

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-cli#42]
I got this stacktrace after installing viur-cli in a fresh python310 env:
```py
$ viur
Traceback (most recent call last):
  File "/home/sven/.local/bin/viur", line 5, in <module>
    from viur_cli import cli
  File "/home/sven/.local/lib/python3.10/site-packages/viur_cli/__init__.py", line 10, in <module>
    from .scriptor import script
  File "/home/sven/.local/lib/python3.10/site-packages/viur_cli/scriptor/__init__.py", line 1, in <module>
    from .cli import script
  File "/home/sven/.local/lib/python3.10/site-packages/viur_cli/scriptor/cli.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I think `requests` is missing here?
https://github.com/viur-framework/viur-cli/blob/3393e54f2e323837d8b7cbe92f855197bfdf7b22/setup.cfg#L22-L27

**Comment by XeoN-GHMB** [comment]
fixed with versio 1.0.6
