### ISSUE TITLE
Cannot use viur-cli 1.1.1 in a Python 3.12 environment

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-cli#92]
When I try to update a pipenv with viur-cli==1.1.1 to Python 3.12, I'm getting dependency mismatch:
```
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 1.1.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 2.0.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 2.1.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 2.1.1 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 2.1.2 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.8; 2.2.1 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.9; 2.3.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.9; 2.3.1 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.9; 2.3.2 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.9; 2.4.0 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.10; 2.4.1 Requires-Python >=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <3.10; 2.4.2 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.10; 2.5.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.11; 2.6.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.11; 2.7.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.12; 2.8.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.12; 2.8.1 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.12; 2.9.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.12
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement python-minifier==2.9.0 (from viur-cli) (from versions: none)
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:       ^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 908, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^^^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 681, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 442, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for python-minifier==2.9.0

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/cli/command.py", line 546, in update
    do_update(
  File "/usr/lib/python3.11/site-packages/pipenv/routines/update.py", line 59, in do_update
    do_lock(
  File "/usr/lib/python3.11/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 849, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 718, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```
As python-minifier was a depenceny of the already removed flare.py, this must be removed as well from the package.

**Comment by Grashalmbeisser** [comment]
is solved with v2.0.0.dev2
